dist: xenial
sudo: required
services:
- docker
language: go
go:
- "1.13.x"

branches:
  only:
    - master

env:
  global:
    GOFLAGS=-mod=vendor

install:
  # This script is used by the Travis build to install a cookie for
  # go.googlesource.com so rate limits are higher when using `go get` to fetch
  # packages that live there.
  # See: https://github.com/golang/go/issues/12933
  - bash scripts/gogetcookie.sh
  - make tools

matrix:
  fast_finish: true
  allow_failures:
    - go: tip
  include:
    - name: "make lintstatic"
      script: GOGC=15 make lintstatic
    - name: "make linttravis1"
      script: GOGC=5 make linttravis1
    - name: "make linttravis2"
      script: GOGC=5 make linttravis2
    - name: "make linttravis3"
      script: GOGC=5 make linttravis3
    - name: "make tflint"
      script: make tflint
    - name: "make test"
      script: make test
    - name: "make website-lint"
      script: make website-lint
    - name: "make website-test"
      script: make website-test
    - name: "make website-registrycheck"
      script: make website-registrycheck
