dist: xenial
sudo: required
services:
- docker
language: go
go:
- "1.13.x"

branches:
  only:
    - master

env:
  global:
    GOFLAGS=-mod=vendor

install:
  # This script is used by the Travis build to install a cookie for
  # go.googlesource.com so rate limits are higher when using `go get` to fetch
  # packages that live there.
  # See: https://github.com/golang/go/issues/12933
  - bash scripts/gogetcookie.sh
  - make tools

matrix:
  fast_finish: true
  allow_failures:
    - go: tip
  include:
    - name: "make lintrest"
      script: GOGC=5 make lintrest
    # results in a OOM error
    #- name: "make lintunused"
    #  script: GOGC=5 make lintunused
    - name: "make tflint"
      script: make tflint
    - name: "make test"
      script: make test
    - name: "make depscheck"
      script: make depscheck
    - name: "make website-lint"
      script:
      - curl -sLo /tmp/terraform.zip https://releases.hashicorp.com/terraform/0.12.18/terraform_0.12.18_linux_amd64.zip
      - unzip /tmp/terraform.zip -d /tmp
      - mv /tmp/terraform .
      - make website-lint
    - name: "make website-test"
      script: make website-test
