run:
  deadline: 30m10s
  modules-download-mode: vendor

issues:
  max-per-linter: 0
  max-same-issues: 0

linters:
  disable-all: true
  enable:
    - unconvert
    - varcheck
    - vet
    - vetshadow
    - whitespace

linters-settings:
  errcheck:
    ignore: github.com/hashicorp/terraform-plugin-sdk/helper/schema:ForceNew|Set,fmt:.*,io:Close
  misspell:
    ignore-words:
      - hdinsight
