---
name: Open Pull Request when an `auto-pr` is pushed for go-azure-sdk

on:
  push:
    branches:
      - 'auto-pr/deps/updating-go-azure-sdk-to-**'

jobs:
  open-pull-request:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

      - name: "open a pull request"
        id: open-pr
        run: |
          version="$(echo {{ github.ref_name }} | sed "s/auto-pr\/deps\/updating-go-azure-sdk-to-//")"
          title="dependencies: updating `hashicorp/go-azure-sdk` to `${version}`"
          
          # this runs everytime the PR gets pushed too, whilst you can only create a PR a single time
          # so we should be smarter, but piping this to /dev/null is a fine workaround for MVP
          gh pr create --title "$title" --body "$PR_BODY" -B "$PR_TARGET" > /dev/null

        env:
          PR_BODY: "This PR updates `hashicorp/go-azure-sdk` - further details can be found in a comment."
          PR_TARGET: "main"
          GH_TOKEN: ${{ secrets.SERVICE_ACCOUNT_TERRAFORM_TOKEN }}
