---
name: Breaking Schema Changes

permissions:
  contents: read
  pull-requests: read


on:
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - '.github/workflows/breaking-change-detection.yaml'
      - 'vendor/**'
      - 'internal/**.go'

concurrency:
  group: 'breakingChange-${{ github.head_ref }}'
  cancel-in-progress: true

jobs:
  detect:
    runs-on: custom-linux-small
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version-file: ./.go-version
      - run: bash ./scripts/run-breaking-change-detection.sh
