name: 'Mark Stale/Close Inactive Draft PRs'
on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * MON'

permissions:
  issues: write
  pull-requests: write

jobs:
  stale-draft-prs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Process stale draft PRs
        run: ./scripts/close-stale-draft-prs.sh -o "${{ github.repository_owner }}" -r "${{ github.event.repository.name }}" -t "${{ secrets.GITHUB_TOKEN }}"

