---
name: Generation Check

permissions:
  contents: read

on:
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - '.github/workflows/gencheck.yaml'
      - '**.go'

concurrency:
  group: 'gencheck-${{ github.head_ref }}'
  cancel-in-progress: true

jobs:
  gencheck:
    runs-on: custom-linux-large
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version-file: ./.go-version
      - run: bash scripts/gogetcookie.sh
      - run: make gencheck
  save-artifacts-on-fail:
    if: ${{ needs.gencheck.result }} == 'failure'
    uses: ./.github/workflows/save-artifacts.yaml
  comment-on-fail:
    if: ${{ needs.depscheck.result }} == 'failure'
    uses: ./.github/workflows/comment-failure.yaml
