---
name: Generation Check

permissions:
  contents: read

on:
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - '.github/workflows/gencheck.yaml'
      - '**.go'

concurrency:
  group: 'gencheck-${{ github.head_ref }}'
  cancel-in-progress: true

jobs:
  gencheck:
    runs-on: custom-linux-large
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: ./.go-version
      - run: bash scripts/gogetcookie.sh
      - run: make gencheck
  save-artifacts-on-fail:
    needs: gencheck
    if: ${{ failure() }}
    uses: ./.github/workflows/save-artifacts.yaml
  comment-on-fail:
    needs: gencheck
    if: ${{ failure() }}
    uses: ./.github/workflows/comment-failure.yaml
