---
name: GoLang Linting

permissions:
  contents: read

on:
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - '.github/workflows/golint.yaml'
      - 'vendor/**'
      - '**.go'

concurrency:
  group: 'golint-${{ github.head_ref }}'
  cancel-in-progress: true

jobs:
  golint:
    runs-on: custom-linux-large
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: ./.go-version
      - uses: golangci/golangci-lint-action@9fae48acfc02a90574d7c304a1758ef9895495fa # v7.0.1
        with:
          version: 'v2.4.0'
          args: -v ./internal/...
  save-artifacts-on-fail:
    needs: golint
    if: ${{ failure() }}
    uses: ./.github/workflows/save-artifacts.yaml
  comment-on-fail:
    needs: golint
    if: ${{ failure() }}
    uses: ./.github/workflows/comment-failure.yaml
