---
name: Increment Milestone

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  issues: write
  contents: read

jobs:
  increment-milestone:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-depth: 0
      - name: "Increment Milestone"
        shell: bash
        run: bash ./scripts/increment-milestone.sh -u https://api.github.com/repos${{ github.owner }}/${{ github.repository }}/milestones -r ${{github.ref_name}} -t ${{secrets.GITHUB_TOKEN}}