---
name: Link Milestone

on:
  pull_request_target:
    branches: [main]
    types: ['closed']

jobs:
  link-milestone:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
    steps:
      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
        with:
          # we cannot use go-version-file here because no repositories are checked out so there is no file to reference
          go-version: '1.25.3'
      - run: |
          go install github.com/stephybun/link-milestone@latest
          link-milestone
        env:
          PR_NUMBER: ${{ github.event.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPO: ${{ github.repository }}
