---
name: PR lint and test
on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']
    paths:
      - '**.go'
      - 'vendor/**'
      - '.github/workflows/**'

jobs:
  configure:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.14.5'
      - run: bash scripts/gogetcookie.sh
      - run: make tools

  lintrest:
    needs: configure
    runs-on: ubuntu-latest
    steps:
      - run: TRAVIS=ci GOGC=5 make lintrest

  tflint:
    needs: configure
    runs-on: ubuntu-latest
    steps:
      - run: TRAVIS=ci make tflint

  test:
    needs: configure
    runs-on: ubuntu-latest
    steps:
      - run: TRAVIS=ci make test

  depscheck:
    needs: configure
    runs-on: ubuntu-latest
    steps:
      - run: make depscheck
