# This is a basic workflow to help you get started with Actions

name: MakeTests


# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      service:
        type: string
        description: the service to be tested
        default: appservice
      tests:
        type: string
        description: the service to be tested
        default: TestAccWindowsFunctionApp

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: azure-sub

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: pwd

      # Runs a set of commands using the runners shell
      - name: Run the tests
        env:
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_ENVIRONMENT: ${{ secrets.ARM_ENVIRONMENT }}
          ARM_METADATA_HOST: ${{ secrets.ARM_METADATA_HOST }}
          ARM_TEST_LOCATION: ${{ secrets.ARM_TEST_LOCATION }}
          ARM_TEST_LOCATION_ALT: ${{ secrets.ARM_TEST_LOCATION_ALT }}
          ARM_TEST_LOCATION_ALT2: ${{ secrets.ARM_TEST_LOCATION_ALT2 }}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}

        run: make acctests SERVICE='${{ github.event.inputs.service }}' TESTARGS='-run=${{ github.event.inputs.tests }}' TESTTIMEOUT='600m'
        
