---
name: Provider Tests
on:
  pull_request:
    types: ["opened", "synchronize"]
    paths:
      - '.github/workflows/provider-test.yaml'
      - 'internal/**.go'
      - 'vendor/github.com/hashicorp/go-azure-sdk/sdk/auth/**'
      - 'vendor/github.com/hashicorp/go-azure-sdk/sdk/environments/**'

permissions:
  contents: read
  id-token: write
  pull-requests: read

jobs:
  secrets-check:
    runs-on: ubuntu-latest
    outputs:
      available: "${{ steps.check-secrets.outputs.available }}"
    steps:
      # we check for the ACTIONS_ID_TOKEN_REQUEST_URL variable as a proxy for other secrets
      # it will be unset when running for a PR from a fork, in which case we don't run these tests
      - id: check-secrets
        run: |
          if [[ "${ACTIONS_ID_TOKEN_REQUEST_URL}" == "" ]]; then
            echo "available=false" | tee ${GITHUB_OUTPUT}
          else
            echo "available=true" | tee ${GITHUB_OUTPUT}
          fi

  provider-tests:
    runs-on: custom-linux-large
    needs: [secrets-check]
    if: needs.secrets-check.outputs.available == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: ./.go-version

      - name: Azure CLI login (using OIDC)
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          allow-no-subscriptions: true

      - name: Run provider tests
        run: make testacc TEST=./internal/provider TESTARGS="-run '^TestAcc'"
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_CERTIFICATE: ${{ secrets.ARM_CLIENT_CERTIFICATE }}
          ARM_CLIENT_CERTIFICATE_PASSWORD: ${{ secrets.ARM_CLIENT_CERTIFICATE_PASSWORD }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}

  save-artifacts-on-fail:
    needs: provider-tests
    if: ${{ failure() }}
    uses: ./.github/workflows/save-artifacts.yaml
  comment-on-fail:
    needs: provider-tests
    if: ${{ failure() }}
    uses: ./.github/workflows/comment-failure.yaml
