---
name: "Pull Request Reviewed"

on:
  pull_request_review:
    types: [submitted]

permissions:
  pull-requests: read

jobs:
  add-or-remove-waiting-response:
    runs-on: ubuntu-latest
    steps:
      - name: "Set Artifacts for add-waiting-response"
        if: github.event.review.state != 'approved' && github.actor != github.event.pull_request.user.login
        shell: bash
        run: |
          mkdir -p wr_actions
          echo ${{ github.owner }} > wr_actions/ghowner.txt
          echo ${{ github.repository }} > wr_actions/ghrepo.txt
          echo ${{ github.event.pull_request.number }} > wr_actions/prnumber.txt
          echo "add-waiting-response" > wr_actions/action.txt
      - name: "Set Artifacts for remove-waiting-response"
        if: github.actor == github.event.pull_request.user.login
        shell: bash
        run: |
          mkdir -p wr_actions
          echo ${{ github.owner }} > wr_actions/ghowner.txt
          echo ${{ github.repository }} > wr_actions/ghrepo.txt
          echo ${{ github.event.pull_request.number }} > wr_actions/prnumber.txt
          echo "remove-waiting-response" > wr_actions/action.txt                
      - uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
        with:
          name: artifact
          path: wr_actions
