name: Save Artifacts

on:
  # This file is reused, and called from other workflows
  workflow_call:

jobs:
  save-artifacts:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          mkdir -p wr_actions
          echo ${{ github.repository_owner }} > wr_actions/ghowner.txt
          echo ${{ github.event.repository.name }} > wr_actions/ghrepo.txt
          echo ${{ github.event.pull_request.number }} > wr_actions/prnumber.txt
      - uses: actions/upload-artifact@1eb3cb2b3e0f29609092a73eb033bb759a334595 # v4.1.0
        with:
          name: artifact
          path: wr_actions
          retention-days: 1
