---
name: Shell Script Linting

permissions:
  contents: read

on:
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - '.github/workflows/shellcheck.yaml'
      - 'scripts/**'

concurrency:
  group: 'shellcheck-${{ github.head_ref }}'
  cancel-in-progress: true

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Run ShellCheck
        run: make shellcheck
  save-artifacts-on-fail:
    needs: shellcheck
    if: ${{ failure() }}
    uses: ./.github/workflows/save-artifacts.yaml
  comment-on-fail:
    needs: shellcheck
    if: ${{ failure() }}
    uses: ./.github/workflows/comment-failure.yaml
