---
name: Static Analysis

permissions:
  contents: read
  pull-requests: read

on:
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - '.github/workflows/static-analysis.yaml'
      - 'vendor/**'
      - 'internal/**.go'

concurrency:
  group: 'staticAnalysys-${{ github.head_ref }}'
  cancel-in-progress: true

jobs:
  detect:
    runs-on: [custom, linux, small]
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version-file: ./.go-version
      - run: bash ./scripts/run-static-analysis.sh