---
name: 32 Bit Build

permissions:
  contents: read
  pull-requests: read

on:
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - '.github/workflows/thirty-two-bit.yaml'
      - 'vendor/**'
      - '**.go'

concurrency:
  group: 'thirtytwo-${{ github.head_ref }}'
  cancel-in-progress: true

jobs:
  compatibility-32bit-test:
    runs-on: custom-linux-small
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        with:
          go-version-file: ./.go-version
      - run: bash scripts/gogetcookie.sh
      - run: GOARCH=386 GOOS=linux go build -o 32bitbuild .
  save-artifacts-on-fail:
    if: ${{ needs.compatibility-32bit-test.result }} == 'failure'
    uses: ./.github/workflows/save-artifacts.yaml
  comment-on-fail:
    if: ${{ needs.depscheck.result }} == 'failure'
    uses: ./.github/workflows/comment-failure.yaml
