---
name: 32 Bit Build

permissions:
  contents: read
  pull-requests: read

on:
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - '.github/workflows/thirty-two-bit.yaml'
      - 'vendor/**'
      - '**.go'

concurrency:
  group: 'thirtytwo-${{ github.head_ref }}'
  cancel-in-progress: true

jobs:
  compatibility-32bit-test:
    runs-on: custom-linux-small
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: ./.go-version
      - run: bash scripts/gogetcookie.sh
      - run: GOARCH=386 GOOS=linux go build -o 32bitbuild .
  save-artifacts-on-fail:
    needs: compatibility-32bit-test
    if: ${{ failure() }}
    uses: ./.github/workflows/save-artifacts.yaml
  comment-on-fail:
    needs: compatibility-32bit-test
    if: ${{ failure() }}
    uses: ./.github/workflows/comment-failure.yaml
