---
name: 32 Bit Build

permissions:
  contents: read
  pull-requests: read

on:
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - '.github/workflows/thirty-two-bit.yaml'
      - 'vendor/**'
      - '**.go'

concurrency:
  group: 'thirtytwo-${{ github.head_ref }}'
  cancel-in-progress: true

jobs:
  compatibility-32bit-test:
    runs-on: custom-linux-small
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version-file: ./.go-version
      - run: bash scripts/gogetcookie.sh
      - run: GOARCH=386 GOOS=linux go build -o 32bitbuild .
  save-artifacts-on-fail:
    if: ${{ needs.compatibility-32bit-test.result }} == 'failure'
    uses: ./.github/workflows/save-artifacts.yaml
  comment-on-fail:
    if: ${{ needs.depscheck.result }} == 'failure'
    uses: ./.github/workflows/comment-failure.yaml
