---
name: Unit Tests

permissions:
  contents: read
  pull-requests: read

on:
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - '.github/workflows/unit-test.yaml'
      - 'go.sum'
      - 'vendor/**'
      - '**.go'

  # Run this workflow on merges that change go.sum on the default branch. The
  # intention is to save a new Go module dependency cache for the default
  # branch. This cache is then available to all workflow runs.
  #
  # Reference: https://docs.github.com/en/actions/reference/workflows-and-actions/dependency-caching?search-overlay-input=github+action+cache+limit+increase&search-overlay-ask-ai=true#restrictions-for-accessing-a-cache
  push:
    branches:
      - main
    paths:
      - '.github/workflows/unit-test.yaml'
      - 'go.sum'

concurrency:
  # Some events do not have a `head_ref`. Fall back to `run_id`.
  # Reference: https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#example-using-a-fallback-value-1
  group: '${{ github.workflow }}-${{ github.head_ref || github.run_id }}'
  cancel-in-progress: true

jobs:
  test:
    runs-on: custom-linux-large
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: ./.go-version
      - name: '[Diagnostic] Report Go module cache and build cache disk usage'
        run: 'du -h -d 0 $(go env GOMODCACHE) $(go env GOCACHE)'
      - run: bash scripts/gogetcookie.sh
      - name: Run tests
        run: go test -v -timeout=30s -parallel=20 -count=1 ./...
        env:
          GITHUB_ACTIONS_STAGE: "UNIT_TESTS"
  save-artifacts-on-fail:
    needs: test
    if: ${{ failure() }}
    uses: ./.github/workflows/save-artifacts.yaml
  comment-on-fail:
    needs: test
    if: ${{ failure() }}
    uses: ./.github/workflows/comment-failure.yaml
