---
name: Validate Examples

permissions:
  contents: read
  pull-requests: read

on:
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - '.github/workflows/validate-examples.yaml'
      - 'examples/**'

concurrency:
  group: 'examples-${{ github.head_ref }}'
  cancel-in-progress: true

jobs:
  website-lint:
    runs-on: [custom, linux, large]
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
        with:
          go-version-file: ./.go-version
      - run: bash scripts/gogetcookie.sh
      - run: make tools
      - run: make validate-examples
  save-artifacts-on-fail:
    if: ${{ needs.website-lint.result }} == 'failure'
    uses: ./.github/workflows/save-artifacts.yaml
