---
name: PR lint and test
on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']
    paths:
      - 'website/**'
      - '.github/workflows/**'

jobs:
  configure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.14.5'
      - run: bash scripts/gogetcookie.sh
      - run: make tools

  website-lint:
    needs: configure
    runs-on: ubuntu-latest
    steps:
      - run: make website-lint

  website-test:
    needs: configure
    runs-on: ubuntu-latest
    steps:
      - run: make website-test
