---
name: Website Linting

permissions:
  contents: read
  pull-requests: read

on:
  pull_request:
    types: ["opened", "synchronize"]
    paths:
      - ".github/workflows/website-lint.yaml"
      - "website/**"
      - "internal/services/**"

jobs:
  website-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: ./.go-version
      - run: bash scripts/gogetcookie.sh
      - run: make tools
      - run: make website-lint
      - run: make document-validate
  save-artifacts-on-fail:
    needs: website-lint
    if: ${{ failure() }}
    uses: ./.github/workflows/save-artifacts.yaml
  comment-on-fail:
    needs: website-lint
    if: ${{ failure() }}
    uses: ./.github/workflows/comment-failure.yaml
