---
name: Website Linting
on:
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - 'website/**'
      - '.github/workflows/**'

jobs:
  website-lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15.5'
      - run: bash scripts/gogetcookie.sh
      - run: make tools
      - run: make website-lint
